version: "3.8"
services:

  uptime-kuma:  
    image: louislam/uptime-kuma:1
    container_name: Uptime-Kuma
    network_mode: host
    volumes:
      - /home/#username/docker/Uptime-Kuma:/app/data
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true

  dozzle:
    container_name: Dozzle
    image: amir20/dozzle:latest
    network_mode: bridge
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 4040:8080
    restart: unless-stopped

  samba:
    image: dperson/samba:latest
    hostname: #Cliente
    container_name: Samba
    network_mode: host
    environment:
      - GROUPID=0
      - NMBD=true
      - SHARE=#Cliente;/Server;yes;no;no;all;#username
      - TZ=America/La_Paz
      - USER=#username;#Contraseña
      - USERID=0
      - WORKGROUP=WORKGROUP
    logging:
      driver: json-file
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/#username/docker:/Server/docker

  duplicati:
    container_name: Duplicati
    ports:
      - 8200:8200
    volumes:
      - /home/#username/docker/Duplicati:/config
      - /root:/source
    image: ghcr.io/linuxserver/duplicati:latest
    restart: unless-stopped

  watchtower:
    container_name: Watchtower
    image: containrrr/watchtower:latest
    network_mode: bridge
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    environment:
      - WATCHTOWER_SCHEDULE=0 40 2 * * 1
      - WATCHTOWER_SCOPE=homeassistant
      - TZ=America/La_Paz
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_INCLUDE_STOPPED=true
      - WATCHTOWER_REMOVE_VOLUMES=true
      - PUID=0
      - PGID=0
    
    
